apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-getparmas
spec:
  inputs:
    resources:
      - name: resource-git-tekton-pipeline
        type: git
    params:
      - name: serviceInfo
        type: string
      - name: datacenterCode
        type: string
      - name: cluster
        type: string
      - name: namespace
        type: string
      - name: internalDomain
        type: string
      - name: externalDomain
        type: string
      - name: ssoUsername
        type: string
        default: '#'
      - name: ssoPassword
        type: string
        default: '#'
      - name: ssoToken
        type: string
        default: '#'
      - name: listingsystemInternalUrl
        type: string
      - name: listingsystemUrl
        type: string
      - name: appDepencySevice
        type: string
        default: '#'
  steps:
    - name: run-task-getparmas
      image: python:2.7.17-buster
      volumeMounts:
        - name: data-volume
          mountPath: /tekton/home/getparams
      workingDir: "$(inputs.resources.resource-git-tekton-pipeline.path)/"
      command:
        - /bin/bash
      args:
        - -c
        - |
          ls -R /tekton/home/getparams 
          pip install requests --index https://pypi.tuna.tsinghua.edu.cn/simple
          python getparams.py $(inputs.params.serviceInfo) $(inputs.params.datacenterCode) $(inputs.params.cluster) $(inputs.params.namespace) $(inputs.params.internalDomain) $(inputs.params.externalDomain) $(inputs.params.ssoUsername) $(inputs.params.ssoPassword) $(inputs.params.ssoToken) $(inputs.params.listingsystemInternalUrl) $(inputs.params.listingsystemUrl) $(inputs.params.appDepencySevice)
  volumes:
    - name: data-volume
      hostPath:
        path: /tekton/home/getparams