apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-getparmas
spec:
  inputs:
    resources:
      - name: resource-git-tekton-pipeline
        type: git
    params:
      - name: serviceInfo
        type: string
      - name: datacenterCode
        type: string
      - name: cluster
        type: string
      - name: namespace
        type: string
      - name: internalDomain
        type: string
      - name: externalDomain
        type: string
      - name: ssoUsername
        type: string
        default: #
      - name: ssoPassword
        type: string
        default: #
      - name: ssoToken
        type: string
        default: #
      - name: listingsystemInternalUrl
        type: string
      - name: listingsystemUrl
        type: string
      - name: appDepencySevice
        type: string
        default: #
  steps:
    - name: run-task-getparmas
      image: python:2.7.17-buster
      volumeMounts:
        - name: data-volume
          mountPath: /tekton/home/getparams
      workingDir: "$(inputs.resources.resource-git-tekton-pipeline.path)/"
      command:
        - /bin/bash
      args:
        - -c
        - |
          python getparams.py $(params.serviceInfo) $(params.datacenterCode) $(params.cluster) $(params.namespace) $(params.internalDomain) $(params.externalDomain) $(params.ssoUsername) $(params.ssoPassword) $(params.ssoToken) $(params.listingsystemInternalUrl) $(params.listingsystemUrl) $(params.appDepencySevice)
          ls -R /tekton/home/getparams 
  volumes:
    - name: data-volume
      hostPath:
        path: /tekton/home/getparams