apiVersion: v1
kind: Secret
metadata:
  name: basic-propublic
  annotations:
    tekton.dev/git-0: https://gitlab.wise-paas.com/ # Described below
type: kubernetes.io/basic-auth
stringData:
  username: he.fei
  password: hF15991964302
  
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-propublic
secrets:
  - name: basic-propublic