apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-create-db
spec:
  workspaces:
  - name: storage
  params:
    - name: gitDirectory
      type: string
    - name: serviceUrl
      type: string
    - name: ssoUrl
      type: string
    - name: clusterinfoDefault
      type: string
    - name: serviceConfigs
      type: string
    - name: serviceName
      type: string
    - name: lastTask
      type: string
  steps:
    - name: run-create-db
      image: harbor.hz.wise-paas.com.cn/app-production/pipeline-task/alpine:1.0.0.9
      resources:
        limits:
          cpu: "50m"
          memory: "128Mi"
          ephemeral-storage: "128Mi"
      workingDir: "$(workspaces.storage.path)/$(params.gitDirectory)/"
      script: |
        path="$(params.serviceName).txt"
        echo "START" > $path
        database=$(cat svs.txt)
        echo $database
        if [ ! -z "${database##*$(params.serviceName)*}" ]
        then
            echo "There is no need to deploy $(params.serviceName)"
            echo "SUCCESS" > $path
        else
            con=true        
            lastFilepath="$(params.lastTask).txt"
            if test ! -f "$lastFilepath"
            then
                echo "$lastFilepath does not exist"
                echo "FAILURE" > $path
                con=false
            else
                res=$(cat ${lastFilepath})
                if [ "$res" != "SUCCESS" ]; then
                    echo "res is ${res}"
                    echo "FAILURE" > $path
                    con=false
                fi
            fi 
            if [ "$con" = true ] ; then
                if [ -d "$(params.serviceName)" ]; then                    
                    rm -rf $(params.serviceName)
                fi
                mkdir $(params.serviceName)
                cd $(params.serviceName) 
                python3 ../createdb.py "$(params.serviceUrl)" "$(params.ssoUrl)" "$(params.clusterinfoDefault)" "../serviceInfo.json" "$(params.serviceName)" "../postgreServiceInfo.json"
                dbresultFile="dbresult.txt"
                if [ ! -f "$dbresultFile" ]; then 
                    echo "dbresultFile is not exist!"
                    echo "FAILURE" > ../$path
                else
                    echo "SUCCESS" > ../$path
                fi                
            fi
        fi  